In [3]:
import numpy as np

array_1d = np.array([1, 2, 3, 4, 5])

print(array_1d)

array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(array_2d)

array_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(array_3d)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [3]:
# Crear un ndarray usando np.array() con un rango de números

Npa = np.array(range(10))

# Mostrar el array

print(Npa)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
Np_cero = np.zeros(10)

Np_cero



array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
Np_cero_int = np.zeros(10, dtype=int)

Np_cero_int



array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
Np_uno = np.ones(10)

Np_uno



array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
Np_relleno = np.full(10,256)

Np_relleno

array([256, 256, 256, 256, 256, 256, 256, 256, 256, 256])

In [10]:
Np_rango = np.arange(10) 
print(Np_rango)




[0 1 2 3 4 5 6 7 8 9]


In [11]:
Np_random_dimensiones = np.random.randint(10, size=(3, 4))

print(Np_random_dimensiones)

[[3 2 2 5]
 [6 4 0 0]
 [8 4 0 8]]


In [13]:

# Crear un array de números de punto flotante

arr = np.array([1.1, 2.1, 3.1])

 

# Convertir el tipo de dato del array a entero

newarr = arr.astype("i") # Imprimir el nuevo array y su tipo de dato 
print(newarr) 
print(newarr.dtype)

[1 2 3]
int32


In [14]:
Np_rango = np.arange(10) # Imprimir el array 
print(Np_rango)

[0 1 2 3 4 5 6 7 8 9]


In [15]:
# Crear un array de dos dimensiones con valores enteros aleatorios

Np_random_dimensiones = np.random.randint(10, size=(3, 4))

# Imprimir el array

print(Np_random_dimensiones)

[[2 3 0 1]
 [5 4 2 7]
 [0 3 4 6]]


In [4]:
# Crear un array de números de punto flotante

arr = np.array([1.1, 2.1, 3.1])

 

# Convertir el tipo de dato del array a entero

newarr = arr.astype("i") # Imprimir el nuevo array y su tipo de dato 
print(newarr) 
print(newarr.dtype)

# Crear un array con valores del 0 al 9 
Np_rango = np.arange(10) # Imprimir el array 
print(Np_rango)


[1 2 3]
int32
[0 1 2 3 4 5 6 7 8 9]


In [5]:
# Crear un array de dos dimensiones con valores enteros aleatorios

Np_random_dimensiones = np.random.randint(10, size=(3, 4))

# Imprimir el array

print(Np_random_dimensiones)

# Ver la forma del array

print("Forma de Np_random_dimensiones:", Np_random_dimensiones.shape)

# Ver el tamaño del array

print("Tamaño de Np_random_dimensiones:", Np_random_dimensiones.size)

# Crear arrays con diferentes tipos de datos

Np_cero = np.zeros(10)

Np_cero_int = np.zeros(10, dtype=int)

 

# Ver el tipo de dato

print("Tipo de dato de Np_cero:", Np_cero.dtype)

print("Tipo de dato de Np_cero_int:", Np_cero_int.dtype)

# Ver el tamaño del elemento en bytes

print("Tamaño de cada elemento en Np_random_dimensiones:", Np_random_dimensiones.itemsize)

[[2 6 6 4]
 [7 9 3 5]
 [0 9 0 0]]
Forma de Np_random_dimensiones: (3, 4)
Tamaño de Np_random_dimensiones: 12
Tipo de dato de Np_cero: float64
Tipo de dato de Np_cero_int: int64
Tamaño de cada elemento en Np_random_dimensiones: 4


In [6]:
# Crear un arreglo con números del 1 al 64

numeros = np.arange(1, 65)

# Cambiar la forma del arreglo a una grilla de 8x8

grilla = numeros.reshape(8, 8)

# Mostrar el resultado

print(grilla)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 24]
 [25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40]
 [41 42 43 44 45 46 47 48]
 [49 50 51 52 53 54 55 56]
 [57 58 59 60 61 62 63 64]]


In [8]:
# Crear un arreglo con 24 elementos

arreglo = np.arange(24)

# Cambiar la forma del arreglo a 4x6

nuevo_arreglo = arreglo.reshape(4, 6)

print(nuevo_arreglo)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [9]:


# Crear dos arreglos aleatorios

Array_1 = np.random.randint(10, size=5)

Array_2 = np.random.randint(10, size=5)

 

# Concatenar los arreglos

Arrays_concatenados = np.concatenate([Array_1, Array_2])

 

print("Array_1:", Array_1)

print("Array_2:", Array_2)

print("Arrays_concatenados:", Arrays_concatenados)

Array_1: [3 8 7 9 8]
Array_2: [8 1 9 2 6]
Arrays_concatenados: [3 8 7 9 8 8 1 9 2 6]


In [10]:
# Crear dos arreglos 2D

Array_1 = np.array([[1, 2, 3], [4, 5, 6]])

Array_2 = np.array([[7, 8, 9], [10, 11, 12]])

 

# Apilar los arreglos verticalmente

Arrays_apilados_verticalmente = np.vstack([Array_1, Array_2])

 

print("Array_1:\n", Array_1)

print("Array_2:\n", Array_2)

print("Arrays_apilados_verticalmente:\n", Arrays_apilados_verticalmente)

Array_1:
 [[1 2 3]
 [4 5 6]]
Array_2:
 [[ 7  8  9]
 [10 11 12]]
Arrays_apilados_verticalmente:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [11]:
# Crear dos arreglos 2D

Array_1 = np.array([[1, 2, 3], [4, 5, 6]])

Array_2 = np.array([[7, 8, 9], [10, 11, 12]])

 

# Apilar los arreglos horizontalmente

Arrays_apilados_horizontalmente = np.hstack([Array_1, Array_2])

 

print("Array_1:\n", Array_1)

print("Array_2:\n", Array_2)

print("Arrays_apilados_horizontalmente:\n", Arrays_apilados_horizontalmente)

Array_1:
 [[1 2 3]
 [4 5 6]]
Array_2:
 [[ 7  8  9]
 [10 11 12]]
Arrays_apilados_horizontalmente:
 [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [12]:
# Crear un arreglo concatenado

Arrays_concatenados = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

 

# Dividir en dos partes usando un punto de corte

Array_partido = np.split(Arrays_concatenados, [2])

 

print("Array_concatenados:", Arrays_concatenados)

print("Array_partido:", Array_partido)

Array_concatenados: [ 1  2  3  4  5  6  7  8  9 10]
Array_partido: [array([1, 2]), array([ 3,  4,  5,  6,  7,  8,  9, 10])]


In [13]:
# Crear un arreglo concatenado

Arrays_concatenados = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

 

# Dividir en tres partes usando dos puntos de corte

Array_partido_2 = np.split(Arrays_concatenados, [2, 8])

 

# Asignar a variables distintas

Parte_1, Parte_2, Parte_3 = Array_partido_2

 

print("Parte_1:", Parte_1)

print("Parte_2:", Parte_2)

print("Parte_3:", Parte_3)

Parte_1: [1 2]
Parte_2: [3 4 5 6 7 8]
Parte_3: [ 9 10]
